functionsDirectory = "C:\\Users\\user\\OneDrive\\Desktop\\citizenai-chatbot\\citizenai\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\user\\OneDrive\\Desktop\\citizenai-chatbot\\citizenai\\public"
publishOrigin = "config"
functions = "C:\\Users\\user\\OneDrive\\Desktop\\citizenai-chatbot\\citizenai\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]